{enemyId: 0,   enemyName: "Deathknight",    speed: 1,    hp: 500,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 4, damage: 10};
var SKELETON_STATS =     {enemyId: 1,   enemyName: "Skeleton",       speed: 1,    hp: 600,    magicArmor: 10, physicalArmor: 0,  flying: false, value: 2,  frameEnd: 4, damage: 10};
var BAT_STATS =          {enemyId: 2,   enemyName: "Bat",            speed: 2,    hp: 300,    magicArmor: 0,  physicalArmor: 0,  flying: true,  value: 1,  frameEnd: 5, damage: 7 };
var OGRE_STATS =         {enemyId: 4,   enemyName: "Ogre",           speed: .75,  hp: 2000,   magicArmor: 10, physicalArmor: 10, flying: false, value: 5,  frameEnd: 6, damage: 20};
var GOBLIN_STATS =       {enemyId: 3,   enemyName: "Goblin",         speed: 1.5,  hp: 400,    magicArmor: 0,  physicalArmor: 5,  flying: false, value: 3,  frameEnd: 3, damage: 10};
var GHOST_STATS =        {enemyId: 5,   enemyName: "Ghost",          speed: 1.5,  hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: true,  value: 1,  frameEnd: 3, damage: 5 };
var BOSSSKELETON_STATS = { enemyId: 6,  enemyName: "BossSkeleton",   speed: .75,  hp: 2500,   magicArmor: 15, physicalArmor: 15, flying: false, value: 10, frameEnd: 4, damage: 25};
var WITCH_STATS =        { enemyId: 7,  enemyName: "Witch",          speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var REAPER_STATS =       { enemyId: 8,  enemyName: "Reaper",         speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var HORSEMAN_STATS =     { enemyId: 9,  enemyName: "Horseman",       speed: 2,    hp: 750,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var JACKO_STATS =        { enemyId: 10, enemyName: "Jacko",          speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var DRAGON_STATS =       { enemyId: 11, enemyName: "Dragon",         speed: 1,    hp: 450,    magicArmor: 30, physicalArmor: 30, flying: true,  value: 1,  frameEnd: 3, damage: 5 };
var GOLEM_STATS =        { enemyId: 12, enemyName: "Golem",          speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 7, damage: 5 };
var IMP_STATS =          { enemyId: 13, enemyName: "Imp",            speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 4, damage: 5 };
var ZOMBIE_STATS =       { enemyId: 14, enemyName: "Zombie",         speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 9, damage: 5 };
var VAMPIRE_STATS =      { enemyId: 15, enemyName: "Vampire",        speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var SLIME_STATS =        { enemyId: 16, enemyName: "Slime",          speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
var MINOTAUR_STATS =     { enemyId: 17, enemyName: "Minotaur",       speed: 1,    hp: 450,    magicArmor: 0,  physicalArmor: 0,  flying: false, value: 1,  frameEnd: 3, damage: 5 };
